### ISSUE TITLE
Spike093#0093

### ISSUE THREAD

**Issue by JoeScatena** [srhinos/rsb#14]

**Comment by srhinos** [comment]
Rainbow Six Discord bot answer

**Comment by spike0093** [comment]
Hey, can you add me on discord Spike093#0093

**Comment by spike0093** [comment]
are you the owner/dev?

**Comment by JoeScatena** [comment]
> Rainbow Six Discord bot answer
> […](#)
> On Feb 23, 2020, at 11:14, spike0093 ***@***.***> wrote: Rainbow Six Discord bot question

are you the owner/dev?

**Comment by srhinos** [comment]
Yes

**Comment by JoeScatena** [comment]
> Yes

Hey, add me on discord Spike093#0093 so we can talk.
