### ISSUE TITLE
FFJR BOT

### ISSUE THREAD

**Issue by Cal-Png** [srhinos/rsb#5]
Hey I am intrested of having the FFJR Bot but need some help! discord name and tag is Callooom#7538

Thanks 
Callooom

**Comment by Ullizzzz** [comment]
Hey there, feel free to reach out on the discord server at discord.gg/bots
This goes under "Rhino server bot" role.

**Comment by srhinos** [comment]
Hey, feel free to join the discord instead and have the conversation there

discord.gg/bots
